version: '3'

services:
  vue_app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      # Montar el código fuente como un volumen
      - ./:/app
      # Excluir node_modules para evitar conflictos
      - /app/node_modules
    environment:
      - NODE_ENV=development
    # Reiniciar automáticamente en caso de fallo
    restart: unless-stopped
    command: npm run dev -- --host